### ISSUE TITLE
Sprint - Entrega 14/09

### ISSUE THREAD

**Issue by lsoaresesilva** [ifpe-cti/pmgus#57]
1. Criar diagrama de classes para representar os dados baseados no arquivo da PM (arquivo Excel). Criar as classes Java - Pedro
2. Falar com o PM e saber o que ele precisa em um relatório. Entrega de um relatório funcional (baseado no formato usado pela PM) no formato PDF - Mateus
3. Identificar os pontos (Lat e Long) dos bairros de Garanhuns e criar um mapa com mapas de calor fictícios - Vinícius

**Comment by viniciussoaresti** [comment]
@MatheusDias18 ?

**Comment by viniciussoaresti** [comment]
@BarrosPedro fazer a pr com as classes do diagrama criadas.

**Comment by viniciussoaresti** [comment]
@BarrosPedro no caso, só as classes do negócio.
