### ISSUE TITLE
Diagrama de Classes

### ISSUE THREAD

**Issue by BarrosPedro** [ifpe-cti/pmgus#65]
![pmgusclassdiagram](https://user-images.githubusercontent.com/36742880/45547617-c08be980-b7f7-11e8-8999-8b85e9c21ad8.png)

**Comment by lsoaresesilva** [comment]
Veja só, alguns pontos: endereço do boletim de ocorrência deve ser uma classe separada (daí município liga-se à endereço e endereço ao boletim). Vítima tbm é uma classe separada.

**Comment by BarrosPedro** [comment]
Ok

**Comment by BarrosPedro** [comment]
![pmgusclassdiagram](https://user-images.githubusercontent.com/36742880/45646121-d966fa00-ba98-11e8-876c-5154f9ef5d69.png)

**Comment by viniciussoaresti** [comment]
@lsoaresesilva favor checar se necessita alguma alteração nesse diagrama.

**Comment by viniciussoaresti** [comment]
[ ] - Arma
[ ] - Municipio
[ ] - Endereco
[ ] - Vítima
[ ] - Unidade Droga
[ ] - Tipo de Droga
[ ] - CVP
[ ] - CVLI
[ ] - Boletim de Ocorrência

**Comment by vinisoaresti** [comment]
Done.
