### ISSUE TITLE
Sprint entrega 21/09

### ISSUE THREAD

**Issue by lsoaresesilva** [ifpe-cti/pmgus#66]
1. Fazer Login
2. Armazenar os dados importados da planilha, no banco de dados (Pedro)
3. Fazer menu da aplicação (usar o menu do Primefaces)

**Comment by viniciussoaresti** [comment]
@MatheusDias18 tu só fala do 1, desenrola aí (qq coisa vê aquele login do firebase, se for botar criptografia e pa acho que ainda tenho exemplo senão tira duvida cmg ou c @lsoaresesilva )

**Comment by viniciussoaresti** [comment]
@eu tô com o 3 então, e como ja tá ai @BarrosPedro tais com o 2

**Comment by lsoaresesilva** [comment]
@MatheusDias18 faz o login com BD tradicional mesmo... Tela, controlador, banco, criptografia (https://www.baeldung.com/sha-256-hashing-java).

**Comment by MatheusDias18** [comment]
Qual criptografia utilizaremos?

**Comment by MatheusDias18** [comment]
Login pronto, faltando apenas o pop up de notificações!

**Comment by viniciussoaresti** [comment]
Movido para issue #72 .
