### ISSUE TITLE
Alterar Seletor De Município no Endereço

### ISSUE THREAD

**Issue by viniciussoaresti** [ifpe-cti/pmgus#84]
Ao invés de utilizar o selectOneListbox, que convenhamos, é meio bugado pra usabilidade, utilizar o oneMenu, como definido neste link: https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml.

**Comment by BarrosPedro** [comment]
Alterado

**Comment by BarrosPedro** [comment]
@viniciussoaresti

**Comment by BarrosPedro** [comment]
@viniciussoaresti

**Comment by MatheusDias18** [comment]
@viniciussoaresti  fechar issue!
