### ISSUE TITLE
Ocorrencia(Resenha Diária) = Implementação Complicadíssima

### ISSUE THREAD

**Issue by viniciussoaresti** [ifpe-cti/pmgus#86]
Pela usabilidade, ficaria melhor o cadastro do endereço IMBUTIDO na ocorrencia, o cadastro de municípios por fora.
Vítima não é classe, é String, se não for um filtro necessário.
Fazer teste separado do Wizard e do OneMenu do primefaces antes de implementar a ocorrencia.

**Comment by MatheusDias18** [comment]
Funcionando. @viniciussoaresti de acordo com @BarrosPedro, fecha a issue!

**Comment by BarrosPedro** [comment]
Ainda não, @viniciussoaresti @MatheusDias18. Tá funcionando, porém ainda precisam ser refeitas algumas coisas. Como tá no titulo da issue, é complicadíssima.

**Comment by fabriciofx** [comment]
@BarrosPedro Qual a razão dessa issue ser "complicadíssima"?

**Comment by viniciussoaresti** [comment]
@BarrosPedro implementou. Issue fechada.
